spring:
  application:
    name: exhibition-service
  
  
  # Azure MySQL (기본 설정)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://dbguidely-exhibition-artwork-services.mysql.database.azure.com:3306/exhibition_db?serverTimezone=UTC&sslMode=REQUIRED&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:dbguidelyexhibitionadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:Guidely!}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: $SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.guidely.exhibitionservice: INFO
    org.springframework.web: WARN

---
# MySQL 프로필 (로컬 개발용)
spring:
  config:
    activate:
      on-profile: mysql
  
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/exhibition_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---
# # Azure 프로덕션 프로필 (MySQL)
# spring:
#   config:
#     activate:
#       on-profile: azure
  
#   datasource:
#     url: ${DATABASE_URL}
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     username: ${DB_USERNAME}
#     password: ${DB_PASSWORD}
#     hikari:
#       maximum-pool-size: 10
#       minimum-idle: 2
#       connection-timeout: 30000
  
#   jpa:
#     hibernate:
#       ddl-auto: validate
#     show-sql: false
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect

# logging:
#   level:
#     com.guidely.exhibitionservice: INFO
#     org.springframework.web: WARN
#     org.hibernate.SQL: ERROR

# ---
# # Docker 개발 환경 (MySQL 유지)
# spring:
#   config:
#     activate:
#       on-profile: docker
  
#   datasource:
#     url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/exhibition_db}
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     username: ${SPRING_DATASOURCE_USERNAME:root}
#     password: ${SPRING_DATASOURCE_PASSWORD:password}
  
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: false
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect 