spring:
  application:
    name: exhibition-service
  
  # 프로필별 데이터소스 설정
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:h2}
  
  # H2 (개발용 기본 설정)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: false
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.guidely.exhibitionservice: INFO
    org.springframework.web: WARN

---
# PostgreSQL 프로필
spring:
  config:
    activate:
      on-profile: postgresql
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/exhibition_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

---
# Azure 프로덕션 프로필
spring:
  config:
    activate:
      on-profile: azure
  
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.guidely.exhibitionservice: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: ERROR

---
# Docker 개발 환경 (MySQL 유지)
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/exhibition_db}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect 